window.OPERATIONSLOGS_MASTER_DATA = {
    "gliders": [
        "524",
        "636",
        "806",
        "819",
        "1UP",
        "7N",
        "A2",
        "A23",
        "A26",
        "DLB",
        "E11",
        "EF",
        "EOK",
        "F5",
        "FDX",
        "FNM",
        "GB1",
        "GBV",
        "GJB",
        "HWP",
        "JAX",
        "JGK",
        "JHW",
        "JRF",
        "JVE",
        "KDK",
        "KHR",
        "MBD",
        "MDK",
        "MF",
        "XY"
    ],
    "names": [
        "LEWIS ARMITAGE",
        "JAIDEN ASH",
        "YOLANDA AZE",
        "NICHOLAS BARNETT",
        "DANIEL BARRACLOUGH",
        "GORDON BASEY",
        "DAVE BELL",
        "DAVE BELLAMY",
        "KIRSTY BENNETT",
        "JULIAN BERKS",
        "WILL BLACKBURN",
        "HENRY BONARIUS",
        "CHARLES BONELLO",
        "MARTIN BOULTON",
        "DAVE BOWES",
        "STEVE BOWLING",
        "LIAM BOWRING",
        "JETHRO BRAY",
        "MATTY BRIGGS",
        "WILLIAM BROADLEY",
        "TONY BROMBY",
        "IAN BURGIN",
        "SEB BURTON",
        "THOMAS BURTON",
        "ANDY BUTLER",
        "CHRIS BUTTRICK",
        "RICHARD CARTER",
        "PAUL CARTMELL",
        "MARK CASS",
        "SERGIO CAZADOR",
        "BEVERLEY CHRIMES",
        "TREVOR CHRIMES",
        "FINLEY COAN",
        "GRAEME COOKSEY",
        "MARTIN CORNER",
        "GEOFF DAVEY",
        "XANDER DAYES",
        "TOMMY DOVER",
        "MIKE DRAYTON",
        "OLIVIA DRUMMOND",
        "FREYA EDWARDS",
        "LAYTON EDWARDS",
        "STEVE ELL",
        "CONNOR ELLIOTT",
        "CALLUM FEARN",
        "PETER FENWICK",
        "HENRY FILLINGHAM",
        "ALISTAIR FINLAY",
        "LLOYD FINLAY",
        "ALEX FOX",
        "BOB FOX",
        "KATE FOX",
        "MATTHEW FOX",
        "MICHAEL FOX",
        "MAL GIBSON",
        "AIDAN GLOVER",
        "JOE GWILT",
        "DAVID HAIGH",
        "SAMUEL HALL",
        "RICHARD HALLIBURTON",
        "MARTIN HARRIS",
        "AARON HARVEY",
        "BOWEN HAYES",
        "COLIN HAYES",
        "JAN VAN DER HOEK",
        "DAVE HOLBORN",
        "MIKE HOLMES",
        "PETER HOLMES",
        "BOB HOLROYD",
        "TIM HOWLE",
        "MEL HOWLEY",
        "JOHN HUNT",
        "HAYLEY JACKSON",
        "SAMUEL JEROME",
        "MIKE JOHNSON",
        "ANNE JONES",
        "BOB JONES",
        "MIKE JORDY",
        "PETER JUDE",
        "TONY KENDALL",
        "BOB KIRBITSON",
        "PATRYCJA KOLODZIEJCZYK",
        "CHARLES KRAJEWSKI",
        "CHRIS KYNMAN",
        "FINDLAY LEDGER",
        "SIMON LEECH",
        "CHRISTOPHER LEES",
        "DEBRA LOCKWOOD",
        "SANDY LOYND",
        "JOHN LUDRECIUS",
        "SIMON MADISSON",
        "NEIL MARCH",
        "JASON MARCHANT",
        "SAM MARCHANT",
        "STEFAN MARINKOVIC",
        "CHRIS MARSDEN",
        "ARCHIE MARSHALL",
        "ANTHONY MCDERMOTT",
        "ANDY MCDONALD",
        "BARRY MCKIERNAN",
        "DICK MIDWINTER",
        "TIMOTHY MILNER",
        "MARCU MOGA",
        "GEORGE MORRIS",
        "JONATHAN MOXON",
        "NICHOLAS NEWITT",
        "NICK NEWITT",
        "JOHN NORMAN",
        "MICK PAGRAM",
        "ROBIN PARKER",
        "DAVE PETERS",
        "MIKE PHILLIPS",
        "MONTY POWELL",
        "CHRIS PRICE",
        "JUSTIN PYTEL",
        "ROHAN RAISBECK",
        "ALAN RANDS",
        "MATTHEW RANDS",
        "BELLA REID",
        "JONATHON RICHARDSON",
        "MARK RIDGER",
        "PATRICIA RIDGER",
        "JIM ROBERTS",
        "MAT ROBERTS",
        "SETH ROCK",
        "DERRICK RODDIE",
        "SAM RODDIE",
        "SUE ROOM",
        "CYPRIAN RUDY",
        "IRENEUSZ RUDY",
        "STEVE RUFFELL",
        "CASPAR SANGWIN",
        "ISAAC SAWYER",
        "MATTHEW SCHREIBER",
        "ROB SCHWAB",
        "CRAIG SCOTT",
        "RODGER SCRIVEN",
        "FREYA SENIOR",
        "PAUL SHAW",
        "DARCEY SMITH",
        "DAVE SMITH",
        "JON SMITH",
        "TONY SNOWDEN",
        "SOLO",
        "ALAN SPENCER",
        "KEITH SPRINGATE",
        "XANDER STILES",
        "ZAK STURDY",
        "BERNIE SVENSON",
        "MATT SWAINSTON",
        "TIM SYKES",
        "CHARLIE TAGG",
        "DAVE TAGG",
        "ANDY THORNHILL",
        "ALFIE THORPE",
        "JOHN TILLSON",
        "DILLON VYAS",
        "GRAHAM WADFORTH",
        "MICHAEL WALKER",
        "STUART WALLACE",
        "BENJAMIN WARD",
        "CONNOR WARREN",
        "PAUL WATSON",
        "HARVEY WEBSTER",
        "SUE WEBSTER",
        "ALAN WEST",
        "RACHEL WESTERBY",
        "STEVE WILKINSON",
        "JOHN WILLIAMS",
        "NICK WONG",
        "MATT WRIGGLESWORTH",
        "BILL YOUNG",
        "PETER ZOCHLING"
    ],
    "tugAircraft": [],
    "tugPilots": [
        "DAVE BELL",
        "WILL BLACKBURN",
        "DAVE CAMPBELL",
        "BOB FOX",
        "MAL GIBSON",
        "DIANE SAYWELL",
        "DAVE HOLBORN",
        "BOB KIRBITSON",
        "ADRIAN LEONING",
        "ROBIN PARKER",
        "SUE ROOM",
        "JON SMITH",
        "GRAHAM WADFORTH",
        "ALAN WEST",
        "STEVE WILKINSON",
        "SELF LAUNCH"
    ],
    "payees": [
        "P1",
        "P2",
        "VOUCHER",
        "SHARE"
    ],
    "runways": [
        "18",
        "36",
        "31",
        "13"
    ]
};
